### get users
GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com"
}

### Get employee by id
GET http://localhost:5000/api/users/1

### Update an employee
PATCH http://localhost:5000/api/users/1
Content-Type: application/json

{
  "firstName": "Ryan",
  "lastName": "Ray",
  "email": "ryan.ray@example.com"
}